from enum import Enum, auto

#TODO DO PRZEMYSLENIA, MOZE ZREZYGNOWAC Z ENUMA I ROBIC STRINGI
class DocumentType(Enum):  # TODO WAIT FOR INFO ABOUT OTHER
    DEATH_CERTIFICATE = auto()
    BIRTH_CERTIFICATE = auto()
    MARRIAGE_CERTIFICATE = auto()
    INHERITANCE_REJECTION = auto()
    OTHER = auto()
