# Generated by Django 4.0.4 on 2022-04-24 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Person first name')),
                ('surname', models.CharField(max_length=30, verbose_name='Person surname')),
                ('pesel', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Pesel must have 11 digits', regex='\\d{11}')], verbose_name='Person pesel')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Person phone number')),
                ('home_address', models.CharField(max_length=50, null=True, verbose_name='Person home address')),
                ('birthday', models.DateField(null=True, verbose_name='Person birthday')),
                ('is_testator', models.BooleanField(default=False, verbose_name='Is person a testator')),
                ('death_date', models.DateField(null=True, verbose_name='Person death date')),
                ('want_inherit', models.BooleanField(default=False, verbose_name='Is person eager to inherit')),
                ('supposed_death_notification', models.DateField(null=True, verbose_name='Person supposed date notification')),
                ('proxy', models.CharField(max_length=60, null=True, verbose_name='Juvenile proxy')),
                ('notes', models.TextField(null=True, verbose_name='Notes for person')),
                ('receive_confirmation_place', models.CharField(max_length=30, null=True, verbose_name='place_of_receive_confirmation')),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30, verbose_name='Document type')),
                ('first_relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_relative', to='gentree.person')),
                ('second_relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_relative', to='gentree.person')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], max_length=30, verbose_name='Document type')),
                ('code', models.CharField(max_length=30, verbose_name='Document code')),
                ('note', models.CharField(max_length=30, verbose_name='Document notes')),
                ('date', models.DateField(null=True, verbose_name='Document date')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gentree.person')),
            ],
        ),
    ]
