# Generated by Django 4.0.4 on 2022-04-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Relations',
            new_name='Relation',
        ),
    ]
