# Generated by Django 4.0.4 on 2022-05-05 19:28

import django.core.validators
from django.db import migrations, models
import sondao.logic.DocumentType
import sondao.logic.RelationTypes


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0002_rename_documents_document_rename_relations_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(1, sondao.logic.DocumentType.DocumentType['DEATH_CERTIFICATE']), (2, sondao.logic.DocumentType.DocumentType['BIRTH_CERTIFICATE']), (3, sondao.logic.DocumentType.DocumentType['MARRIAGE_CERTIFICATE']), (4, sondao.logic.DocumentType.DocumentType['INHERITANCE_REJECTION']), (5, sondao.logic.DocumentType.DocumentType['OTHER'])], max_length=30, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Person birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Person death date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Person home address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes for person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Pesel must have 11 digits', regex='\\d{11}')], verbose_name='Person pesel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Person phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='proxy',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Juvenile proxy'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receive_confirmation_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Place of received confirmation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='supposed_death_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Person supposed date notification'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[(1, sondao.logic.RelationTypes.RelationTypes['CHILD']), (2, sondao.logic.RelationTypes.RelationTypes['FULL_ADOPTED_CHILD']), (3, sondao.logic.RelationTypes.RelationTypes['PARTIAL_ADOPTED_CHILD']), (4, sondao.logic.RelationTypes.RelationTypes['SIBLING']), (5, sondao.logic.RelationTypes.RelationTypes['PARENT']), (6, sondao.logic.RelationTypes.RelationTypes['FULL_ADOPTED_PARENT']), (7, sondao.logic.RelationTypes.RelationTypes['PARTIAL_ADOPTED_PARENT']), (8, sondao.logic.RelationTypes.RelationTypes['SPOUSE']), (9, sondao.logic.RelationTypes.RelationTypes['EX_SPOUSE'])], max_length=30, verbose_name='Document type'),
        ),
    ]
