# Generated by Django 4.0.4 on 2022-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0003_alter_document_type_alter_person_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Document date'),
        ),
    ]
