# Generated by Django 4.0.4 on 2022-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0004_alter_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Person pesel'),
        ),
    ]
