# Generated by Django 4.0.4 on 2022-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0005_alter_person_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('CHILD', 1), ('FULL_ADOPTED_CHILD', 2), ('PARTIAL_ADOPTED_CHILD', 3), ('SIBLING', 4), ('PARENT', 5), ('FULL_ADOPTED_PARENT', 6), ('PARTIAL_ADOPTED_PARENT', 7), ('SPOUSE', 8), ('EX_SPOUSE', 9)], max_length=30, verbose_name='Document type'),
        ),
    ]
