# Generated by Django 4.0.5 on 2022-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0007_alter_relation_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('DEATH_CERTIFICATE', 'DEATH_CERTIFICATE'), ('BIRTH_CERTIFICATE', 'BIRTH_CERTIFICATE'), ('MARRIAGE_CERTIFICATE', 'MARRIAGE_CERTIFICATE'), ('INHERITANCE_REJECTION', 'INHERITANCE_REJECTION'), ('OTHER', 'OTHER')], max_length=30, verbose_name='Document type'),
        ),
    ]
