# Generated by Django 4.0.5 on 2022-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0008_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('DEATH_CERTIFICATE', 'Death certificate'), ('BIRTH_CERTIFICATE', 'Birth certificate'), ('MARRIAGE_CERTIFICATE', 'Marriage certificate'), ('INHERITANCE_REJECTION', 'Inheritance rejection'), ('OTHER', 'Other')], max_length=30, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('CHILD', 'Child'), ('FULL_ADOPTED_CHILD', 'Full adopted child'), ('PARTIAL_ADOPTED_CHILD', 'Partial adopted child'), ('SIBLING', 'Sibling'), ('PARENT', 'Parent'), ('FULL_ADOPTED_PARENT', 'Full adopted parent'), ('PARTIAL_ADOPTED_PARENT', 'Partial adopted parents'), ('SPOUSE', 'Spouse'), ('EX_SPOUSE', 'Ex-spouse')], max_length=30, verbose_name='Relation type'),
        ),
    ]
