# Generated by Django 4.0.5 on 2022-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentree', '0009_alter_document_type_alter_relation_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='person_id',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('CHILD', 'Child'), ('FULL_ADOPTED_CHILD', 'Full adopted child'), ('PARTIAL_ADOPTED_CHILD', 'Partial adopted child'), ('SIBLING', 'Sibling'), ('PARENT', 'Parent'), ('FULL_ADOPTED_PARENT', 'Full adopted parent'), ('PARTIAL_ADOPTED_PARENT', 'Partial adopted parent'), ('SPOUSE', 'Spouse'), ('EX_SPOUSE', 'Ex-spouse')], max_length=30, verbose_name='Relation type'),
        ),
    ]
